from controlbox.modules.staging_sites.domain.entities import (
    SslStatus,
    StagingDomainMode,
    StagingSite,
    StagingSourceType,
    StagingStackType,
    StagingStatus,
)
from controlbox.modules.staging_sites.infrastructure.models import StagingSiteModel


def staging_to_entity(model: StagingSiteModel) -> StagingSite:
    return StagingSite(
        id=model.id,
        tenant_id=model.tenant_id,
        source_type=StagingSourceType(model.source_type),
        source_id=model.source_id,
        source_domain=model.source_domain,
        name=model.name,
        domain=model.domain,
        domain_mode=StagingDomainMode(model.domain_mode),
        stack_type=StagingStackType(model.stack_type),
        runtime_version=model.runtime_version,
        status=StagingStatus(model.status),
        ssl_enabled=model.ssl_enabled,
        ssl_status=SslStatus(model.ssl_status),
        container_name=model.container_name,
        nginx_container_name=model.nginx_container_name,
        php_container_name=model.php_container_name,
        site_path=model.site_path,
        traefik_router=model.traefik_router,
        managed_database_id=model.managed_database_id,
        database_user_id=model.database_user_id,
        database_config=dict(model.database_config or {}),
        public_access_blocked=model.public_access_blocked,
        last_sync_at=model.last_sync_at,
        last_sync_type=model.last_sync_type,
        last_sync_direction=model.last_sync_direction,
        cpu_usage_percent=model.cpu_usage_percent,
        memory_used_mb=model.memory_used_mb,
        disk_used_mb=model.disk_used_mb,
        settings=dict(model.settings or {}),
        error_message=model.error_message,
        task_id=model.task_id,
        created_at=model.created_at,
        updated_at=model.updated_at,
    )


def staging_to_model(entity: StagingSite) -> StagingSiteModel:
    return StagingSiteModel(
        id=entity.id,
        tenant_id=entity.tenant_id,
        source_type=entity.source_type.value,
        source_id=entity.source_id,
        source_domain=entity.source_domain,
        name=entity.name,
        domain=entity.domain,
        domain_mode=entity.domain_mode.value,
        stack_type=entity.stack_type.value,
        runtime_version=entity.runtime_version,
        status=entity.status.value,
        ssl_enabled=entity.ssl_enabled,
        ssl_status=entity.ssl_status.value,
        container_name=entity.container_name,
        nginx_container_name=entity.nginx_container_name,
        php_container_name=entity.php_container_name,
        site_path=entity.site_path,
        traefik_router=entity.traefik_router,
        managed_database_id=entity.managed_database_id,
        database_user_id=entity.database_user_id,
        database_config=entity.database_config,
        public_access_blocked=entity.public_access_blocked,
        last_sync_at=entity.last_sync_at,
        last_sync_type=entity.last_sync_type,
        last_sync_direction=entity.last_sync_direction,
        cpu_usage_percent=entity.cpu_usage_percent,
        memory_used_mb=entity.memory_used_mb,
        disk_used_mb=entity.disk_used_mb,
        settings=entity.settings,
        error_message=entity.error_message,
        task_id=entity.task_id,
        created_at=entity.created_at,
        updated_at=entity.updated_at,
    )
