"""PHP extension catalog and per-site Dockerfile rendering.

Extensions are installed on top of the site's base PHP image using the
``install-php-extensions`` helper (https://github.com/mlocati/docker-php-extension-installer),
which handles system dependencies automatically. The site's PHP service switches
to a small ``build`` context only when at least one extension is selected, so
sites without custom extensions keep using the plain image unchanged.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import TYPE_CHECKING

from controlbox.shared.infrastructure.docker.env import docker_subprocess_env

if TYPE_CHECKING:
    from controlbox.config.settings import Settings

# Subdirectory (inside the site folder) that holds the generated Dockerfile.
# Kept separate so the Docker build context stays tiny.
PHP_BUILD_DIR = "php-build"
PHP_BUILD_DOCKERFILE = "Dockerfile"

# id -> the name understood by install-php-extensions.
PHP_EXTENSION_CATALOG: list[dict[str, str]] = [
    {"id": "mysqli", "label": "mysqli", "group": "Databases"},
    {"id": "pdo_mysql", "label": "pdo_mysql", "group": "Databases"},
    {"id": "pgsql", "label": "pgsql", "group": "Databases"},
    {"id": "pdo_pgsql", "label": "pdo_pgsql", "group": "Databases"},
    {"id": "pdo_sqlsrv", "label": "pdo_sqlsrv (SQL Server)", "group": "Databases"},
    {"id": "mongodb", "label": "mongodb", "group": "Databases"},
    {"id": "redis", "label": "redis", "group": "Caching"},
    {"id": "memcached", "label": "memcached", "group": "Caching"},
    {"id": "apcu", "label": "apcu", "group": "Caching"},
    {"id": "opcache", "label": "opcache", "group": "Caching"},
    {"id": "igbinary", "label": "igbinary", "group": "Caching"},
    {"id": "gd", "label": "gd", "group": "Images & media"},
    {"id": "imagick", "label": "imagick", "group": "Images & media"},
    {"id": "exif", "label": "exif", "group": "Images & media"},
    {"id": "intl", "label": "intl", "group": "Utilities"},
    {"id": "zip", "label": "zip", "group": "Utilities"},
    {"id": "bcmath", "label": "bcmath", "group": "Utilities"},
    {"id": "gmp", "label": "gmp", "group": "Utilities"},
    {"id": "calendar", "label": "calendar", "group": "Utilities"},
    {"id": "mbstring", "label": "mbstring", "group": "Utilities"},
    {"id": "curl", "label": "curl", "group": "Network"},
    {"id": "soap", "label": "soap", "group": "Network"},
    {"id": "sockets", "label": "sockets", "group": "Network"},
    {"id": "ldap", "label": "ldap", "group": "Network"},
    {"id": "imap", "label": "imap", "group": "Network"},
    {"id": "ssh2", "label": "ssh2", "group": "Network"},
    {"id": "xsl", "label": "xsl", "group": "Utilities"},
    {"id": "sodium", "label": "sodium", "group": "Utilities"},
    {"id": "xdebug", "label": "xdebug", "group": "Debug"},
]

_VALID_EXTENSION_IDS = {item["id"] for item in PHP_EXTENSION_CATALOG}


def normalize_extensions(extensions: list[str] | None) -> list[str]:
    """Keep only known extension ids, de-duplicated and sorted for stability."""
    if not extensions:
        return []
    seen: set[str] = set()
    result: list[str] = []
    for raw in extensions:
        ext = str(raw).strip().lower()
        if ext in _VALID_EXTENSION_IDS and ext not in seen:
            seen.add(ext)
            result.append(ext)
    return sorted(result)


def render_php_dockerfile(base_image: str, extensions: list[str]) -> str:
    """Render a Dockerfile that adds the selected extensions to ``base_image``."""
    ext_args = " ".join(normalize_extensions(extensions))
    return f"""# Generated by ControlBox — do not edit by hand.
FROM {base_image}
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions \\
    && install-php-extensions {ext_args}
"""


def write_php_build_files(site_path: Path, base_image: str, extensions: list[str]) -> bool:
    """Write ``php-build/Dockerfile`` for the selected extensions.

    Returns ``True`` when a build is required (at least one valid extension),
    ``False`` otherwise (the site keeps using the plain image).
    """
    normalized = normalize_extensions(extensions)
    if not normalized:
        return False
    try:
        build_dir = site_path / PHP_BUILD_DIR
        build_dir.mkdir(parents=True, exist_ok=True)
        (build_dir / PHP_BUILD_DOCKERFILE).write_text(
            render_php_dockerfile(base_image, normalized), encoding="utf-8"
        )
    except OSError:
        return False
    return True


def php_image_tag(site_short: str) -> str:
    return f"controlbox-php-{site_short.lower()}:latest"


async def build_php_extension_image(
    settings: "Settings",
    site_path: Path,
    base_image: str,
    site_short: str,
    extensions: list[str] | None,
) -> str | None:
    """Build a per-site PHP image with the selected extensions installed.

    Returns the resulting image tag, or ``None`` when no extension is selected
    (the caller should then fall back to the plain ``base_image``).
    Raises ``RuntimeError`` when the docker build fails.
    """
    normalized = normalize_extensions(extensions)
    if not normalized:
        return None
    if not write_php_build_files(site_path, base_image, normalized):
        raise RuntimeError("No se pudo escribir el Dockerfile de extensiones PHP")
    tag = php_image_tag(site_short)
    build_dir = site_path / PHP_BUILD_DIR
    proc = await asyncio.create_subprocess_exec(
        "docker",
        "build",
        "--pull",
        "-t",
        tag,
        str(build_dir),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
        env=docker_subprocess_env(settings),
    )
    stdout, _ = await proc.communicate()
    if proc.returncode != 0:
        output = stdout.decode(errors="replace") if stdout else ""
        tail = "\n".join(output.strip().splitlines()[-15:])
        raise RuntimeError(f"Falló la compilación de extensiones PHP:\n{tail}")
    return tag
